@startuml
caption <color:#2E7D32>added</color> or <color:#C62828><s>removed</s></color>
participant "<color:#C62828><s>Browser</s></color>" as Browser #FFEBEB
participant "<color:#C62828><s>Backend</s></color>" as Backend #FFEBEB
participant "<color:#C62828><s>DB</s></color>" as DB #FFEBEB
Browser -[#C62828]> Backend: <color:#C62828><s>List owners</s></color>\n<color:#C62828><s>GET /api/owners</s></color>
Backend -[#C62828]> Backend: <color:#C62828><s>OwnerRepository.findByLastNameStartingWith ↗</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>OwnerRepository.findByLastNameStartingWith</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]-> Browser: <color:#C62828><s>200</s></color>
Browser -[#C62828]> Backend: <color:#C62828><s>List owners</s></color>\n<color:#C62828><s>GET /api/owners</s></color>
Backend -[#C62828]> Backend: <color:#C62828><s>OwnerRepository.findByLastNameStartingWith ↗</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>OwnerRepository.findByLastNameStartingWith</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select visits</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]> DB: <color:#C62828><s>select pets</s></color>
Backend -[#C62828]-> Browser: <color:#C62828><s>200</s></color>
@enduml
